server:
  port: 7970

spring:
  application:
    name: tx-manager
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  redis 的设置信息. 线上请用Redis Cluster
  redis:
   host: 127.0.0.1
   port: 6379
   password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30000/eureka/ # 可配置多个地址
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true   #服务之间调用时，指定IP调用
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    appname:  transaction-manager


tx-lcn:
  manager:
    host: 127.0.0.1 # TM监听IP. 默认为 127.0.0.1
    port: 8070 # TM监听Socket端口. 默认为 ${server.port} - 100
    heart-time: 300000 # 心跳检测时间(ms). 默认为 300000
    dtx-time: 8000 #  分布式事务执行总时间(ms). 默认为36000
    concurrent-level: 160 # 事务处理并发等级. 默认为机器逻辑核心数5倍
    admin-key: admin # TM后台登陆密码，默认值为codingapi
    dtx-lock-time: ${tx-lcn.manager.dtx-time} # 分布式事务锁超时时间 默认为-1，当-1时会用tx-lcn.manager.dtx-time的时间
    seq-len: 12  #  雪花算法的sequence位长度，默认为12位.
    ex-url-enabled: false # 异常回调开关。开启时请制定ex-url
    ex-url: /provider/email-to/***@**.com # 事务异常通知（任何http协议地址。未指定协议时，为TM提供内置功能接口）。默认是邮件通知
  message:
    netty:
      attr-delay-time: ${tx-lcn.manager.dtx-time} # 参数延迟删除时间单位ms  默认为dtx-time值
 # 开启日志,默认为false
  logger:
     driver-class-name: ${spring.datasource.driver-class-name}
     jdbc-url: ${spring.datasource.url}
     username: ${spring.datasource.username}
     password: ${spring.datasource.password}


